AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda Layers Test

Resources:
  MyLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.6
        - python3.7
        - python3.8
      CompatibleArchitectures:
        - x86_64
      Content:
        S3Bucket: bucket-name
        S3Key: <s3_key>/<zip_file_name>.zip
      Description: My python package layer
      LayerName: my-python-package-layer
      LicenseInfo: MIT